version: '3.7'

services:

  app:
    build: .
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=interdivisa_bot
      - BOT_TOKEN=${BOT_TOKEN}
      - ORM_ENTITIES=${ORM_ENTITIES}
    ports:
      - 3000:3000
    volumes:
      - "./:/src/"
      - /src/node_modules
    depends_on:
      - postgres
    command: "yarn start:dev"
    networks:
      - intdivbot-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interdivisa_bot
    expose:
      - 5432
    networks:
      - intdivbot-network
    volumes:
      - intdivbot-psg-data:/var/lib/postgresql/data

  # Adminer
  adminer:
    image: adminer
    restart: always
    environment:
      - 'ADMINER_DEFAULT_DB_DRIVER=pgsql'
      - 'ADMINER_DEFAULT_DB_HOST=postgres'
      - 'ADMINER_DEFAULT_DB_NAME=interdivisa_bot'
    depends_on:
      - postgres
    ports:
      - 8981:8080
    networks:
      - intdivbot-network

networks:
  intdivbot-network:

volumes:
  intdivbot-psg-data:
