name: interdivisa-bot
services:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: german-bortoli/interdivisa-bot
    name: interdivisa-bot
