apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: gcr.io/interdivisas-bot/node-kubernetes:v0.1.0 # update
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: POSTGRES_DB
          value: "interdivisa_bot"
        - name: POSTGRES_HOST
          value: "postgres.default"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_password
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: bot_token
      restartPolicy: Always
