apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  db_user: aW50ZGl2X2JvdA==
  db_password: Mnl7Unp0VTNyNDlUfn43Mw==
  bot_token: MTM5NTkyODY1ODpBQUhlcGVseXhEVW9fNGxGMFNUX1Brb0JGalcyVXVISTlfTQ==
